export const LOAD_APP_ROOT = 'LOAD_APP_ROOT';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_SELECTED_QUESTIONS = 'LOAD_SELECTED_QUESTIONS';
export const UPDATE_SELECTED_QUESTIONS = 'UPDATE_SELECTED_QUESTIONS';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';